consumet/consumet.ts

- docs/providers/anilist.md
- package-lock.json
- src/providers/meta/anilist.ts
Adds recommendations to AniList's fetchAnimeInfo function now.
Idk but I tested the changes, and they work
Yes, I'm the goat.
**Summary**
I used the animeinfo fetch query to more of its potential by parsing the recommendations it gives depending on the animeId. It returns an array of recommendations and gives relevant information like Id, Title, Status, Episodes, Image, Cover, Score, etc.
I needed this to add to my personal website, and Riimuru was big busy, so he told me to do it. I solved the problem of no recommendations W me.
Here is whats returned
` recommendations: [ 
{
id: 101921,
idMal: 37999,
title: {
romaji: 'Kaguya-sama …
> feat (anilist): added recommendations

- src/providers/meta/anilist.ts
- test/meta/anilist.test.ts
bugfix: fixes issues where dub would return on non-dub animes.
ye
no
**Summary**
If no dub episodes found, then return empty array.
hola
> fix: dub episodes returning a sub id despite not having dub episodes

- docs/providers/9anime.md
- docs/providers/anilist.md
- docs/providers/animefox.md
- docs/providers/animepahe.md
- docs/providers/animixplay.md
- docs/providers/enime.md
- docs/providers/flixhq.md
- docs/providers/gogoanime.md
- docs/providers/mangadex.md
- docs/providers/mangahere.md
- docs/providers/mangakakalot.md
- docs/providers/mangasee123.md
- docs/providers/readlightnovels.md
- docs/providers/zoro.md
- Fixes code examples used in the docs
- **Yes**
**Summary**
- In short, all the code examples in the docs were missing a closing parenthesis to end the `.then` statement.
> Fixes examples in docs

- dist/providers/manga/mangadex.js
- docs/providers/mangadex.md
- src/providers/manga/mangadex.ts
Minor spelling correction.
Not relevant.
Relevant documentation was already correct, unrelated correction is waiting to be merged.
**Summary**
Fixed typo "altTtitles" in MangaDex 'search' route's response.
None.
> fixed typo

- src/providers/anime/gogoanime.ts
This pr changes the default Gogo server from GogoCDN to Vidstreaming to fix mostly all failed video issues.
N/A
N/A
**Summary**
N/A
N/A
> Change default Gogo Server to VidStreaming

- src/providers/anime/animefox.ts
- src/providers/anime/animepahe.ts
- src/providers/anime/enime.ts
- Fix animepahe not returning episodes (each anime will be set to where it contains both sub/dub since it's impossible to know if they have sub or dub)
- fix enime not returning any episodes if no provider is set (default is gogoanime)
no
no
**Summary**
no
> Fixed minor issues with some providers

- src/providers/anime/gogoanime.ts
This pull request fixes gogo anime's fetchEpisodeSources function logging errors to the console.
No
N/A
**Summary**
I am not sure if that line is deliberately there, but it is extremely annoying to get errors in the console when I am catching errors thrown from the function.
N/A
> Stop sending errors to the console

- src/providers/anime/zoro.ts
Fixed a bug where, when searching for a keyword with an exceded page limit sets hasNextPage to be true, where it should be false.
For example: 
In this example, I am searching for the keyword a, I did a little digging and found that the max page limit for the keyword "a" is 49. So the page limit 50 should show that hasNextPage is false.
> fix (zoro): hasNextPage returning true, when it's false

- src/providers/anime/marin.ts
> fixed marin

- src/providers/anime/9anime.ts
- src/providers/meta/anilist.ts
fixes fetching sub/dub for nineanime
**Summary**
> fix: scraping sub/dub info now works for nineanime

- docs/guides/manga.md
- docs/providers/mangahost.md
- src/providers/manga/index.ts
- src/providers/manga/mangahost.ts
- test/manga/mangahost.test.ts
- Adds a new manga provider.
- Yes, just a basic one but if needed I can add more.
- Yes.
**Summary**
- Adds a new Manga provider called MangaHost (provides brazilian-portuguese scans 🇧🇷)
- Added search, fetchMangaInfo and fetchChapterImages functions.
```ts
mangahost.search("punpun").then(data => {
console.log(data);
})
mangahost.fetchMangaInfo("oyasumi-punpun-mh34076").then(data => {
console.log(data);
})
mangahost.fetchChapterPages("oyasumi-punpun-mh34076/1").then(data => {
console.log(data);
})
```
- Added test.
- Updated docs with example usage.
I added this provider because I'm currently working on a manga reading app and …
> feat: adding MangaHost manga provider

- src/providers/meta/tmdb.ts
it wasn't fixed in earlier pr.
> fix tmdb_id mapping

- src/extractors/rapidcloud.ts
Fixes an issue where intro information would be omitted from the response even though it was available. 
**Summary**
When using the zoro provider intro information was no longer being provided. The information was currently only being added if the host included _rapid-cloud.co_. This fix ensures that the information is included in the response when available. I believe this was also mentioned in #368.
> fix(rapidcloud): include intro if available

- src/providers/anime/gogoanime.ts
Fixes an issue causing the ID returned in the info response to always be: _gogoanimehd.io_
**Summary**
Currently, the ID in the info response is always the same.  This is caused by the following lines, where we initially set the ID to the URL, and then repeat it, making it appear twice. The result of this was only used for extracting the ID, and was then overwritten.
https://github.com/consumet/consumet.ts/blob/56f2f6b519240a001330493b6d19649f97ee74a1/src/providers/anime/gogoanime.ts#L74-L88
The fix is to simply use said ID(now URL) when extracting the ID, making sure that we can still accept URLs as input.
> fix(gogoanime): fix invalid id in info response

- src/providers/anime/zoro.ts
**Issue**
Zoro Get Anime Info only returns ```subOrDub: "sub"``` despite of having both sub and dub available.
***Example***
https://api.consumet.org/anime/zoro/info?id=spy-x-family-17977 returns ```subOrDub: "sub"``` but this has both sub and dub available.
Fixed subOrDub also updated the hasSub and hasDub attributes.
> fix: Zoro subOrDub fix with hasSub and hasDub add

- src/extractors/vidcloud.ts
Solved a bug when trying to extract source url at flixHQ.
No, bug the tests related to the functionality is working now.
No
**Summary**
Closes #569
> bugfix: extract url source at flixhq 

- src/providers/anime/gogoanime.ts
Scrape gogoanime search results' titles using .text() instead of .attr(title). 
Some title attributes are invalid, such as Oshi No Ko's, causing an empty title.
> Fix title scrape in GogoAnime search()

- src/providers/anime/gogoanime.ts
Change `.includes('dub')` to `.includes('(dub)')`.
A title can be falsely filtered as a dubbed show. E.g. "Dubu Wangu".
> fix(gogoanime): include brackets in subOrDub filter

- dist/providers/meta/anilist.js
- dist/providers/meta/mal.js
- docs/providers/anilist.md
- src/providers/meta/anilist.ts
- src/providers/meta/mal.ts
- Updated Kitsu GraphQL and media URLs from `kitsu.io` to `kitsu.app`.
- Fixes `404` errors caused by Kitsu's recent domain and CDN switch.
- Affected files: `anilist.js`, `mal.js`, `anilist.ts`, `mal.ts`, and docs.
---
This PR is a bugfix.
No new tests were added since this is a straightforward URL update. The existing tests should cover the relevant functionality.
Yes, the documentation has been updated to reflect the new Kitsu URLs.
**Summary**
This PR resolves an issue where Kitsu images were returning `404` errors due to their recent domain and CDN change from `kitsu.io` to `kitsu.app`. By updating the URLs, this ensures that all Kitsu-based …
> Update Kitsu GraphQL and Media URLs to New Domain

- src/providers/anime/zoro.ts
- src/providers/meta/anilist.ts
- test/anime/zoro.test.ts
fix anilist type issue 
feat zoro new methods fetchSubbedAnime, fetchDubbedAnime, fetchMovie, fetchTV, fetchOVA, fetchONA, fetchSpecial, fetchGenres, genreSearch
Yes
> feat(zoro): new methods + fix(anilist): type issue

- src/providers/anime/gogoanime.ts
This was a breaking change before, causing URL variables to have double forward slashes after `baseUrl` and breaking usage of `.split('/')[x]`.
> fix(gogoanime): Removed trailing forward slash in baseUrl
