LICENSE, README.md
- added mit license
- added license to readme
=> feat [skip ci]: added license

README.md, docs/guides/anime.md, docs/guides/books.md, docs/guides/comics.md, docs/guides/light-novels.md, docs/guides/manga.md, docs/guides/movies.md, docs/providers/animepahe.md, docs/providers/flixhq.md, docs/providers/gogoanime.md, docs/providers/mangadex.md, docs/providers/readlightnovels.md, src/models/types.ts, src/providers/anime/animepahe.ts, src/providers/anime/gogoanime.ts, src/providers/anime/index.ts, src/utils/extractors/index.ts, src/utils/extractors/kwik.ts, src/utils/index.ts, src/utils/providers-list.ts, test/anime/animepahe.test.ts, test/anime/gogoanime.test.ts
- Added animepahe provider
- Added kwik extractor
- refactored some code
- added tests for animepahe & fixed gogoanime tests
=> feat(anime): added animepahe provider

src/providers/comics/getComics.ts
Small, but urgent fix to getComics.
=> FIX: fixed getComcis page

docs/guides/manga.md, docs/providers/mangahere.md, src/models/manga-parser.ts, src/providers/manga/index.ts, src/providers/manga/mangahere.ts, src/providers/movies/flixhq.ts, src/utils/providers-list.ts, test/manga/mangahere.test.ts
- Added mangahere provider
Not yet
=> feat: MangaHere

docs/providers/mangadex.md
Fix typo in Mangadex docs.
Not needed?
Pretty much the only thing I did.
=> fix Mangadex docs' typo

src/providers/meta/anilist.ts
Basically a 2 character replace fix lol. cheers.
=> fix (anilist): fix episodes number bug

src/providers/meta/anilist.ts, src/utils/utils.ts
Adds country to airingschedule
no
no
**Summary**
Want to filter out Chinese anime
im the goat
=> feat (anilist) Added country to airingschedule

src/providers/anime/enime.ts, src/providers/meta/anilist.ts
* added fallback to enime on search
* Improved Crunchyroll mapping
=> feat: bug fixes

src/providers/manga/mangadex.ts
* Fixes managdex null page numbers in issue [#107](https://github.com/consumet/consumet.ts/issues/107)
=> Improvments

src/providers/meta/mal.ts
=> fixed maths

src/extractors/streamsb.ts
StreamSB fix.
Yes. I have tested it.
**Summary**
StreamSB changed their hosts to `sources48`. `watchsb` header also changed to `sbstream`.
=> StreamSB Fix

src/providers/meta/mal.ts
=> fixed mal stuff

docs/guides/anime.md, docs/guides/manga.md, docs/guides/meta.md, docs/guides/movies.md
Documented some common methods across providers, if it's acceptable like that then i will do the others too. 
No
Yes
**Summary**
new to consumet and found lack of documentation for providers methodes that are needed for smooth experience, hopefully this changes will make it a bit easier for others to join the project.
highly suggest the [stremio-addon-sdk github repo](https://github.com/Stremio/stremio-addon-sdk) as reference for a clear documentation
=> added Common Methods docs

src/providers/anime/tenshi.ts, src/providers/manga/mangadex.ts, src/providers/meta/anilist.ts, src/providers/meta/mal.ts
Reverse manga info chapter order so it starts at 1 instead of the last chapter
=> reverse mangaInfo chapter order

src/providers/movies/dramacool.ts, src/providers/movies/index.ts, src/utils/providers-list.ts, test/movies/dramacool.test.ts
=> feat(dramacool) add dramacool provider

src/providers/meta/tmdb.ts
fix page and add other pagination values
=> fix(TMDB) fix page and add other pagination values

src/extractors/rapidcloud.ts
Changes the URL of the key used by rapidcloud.
**Summary**
rapidclown can be a bit inconsistent at times, so it's better to use my repository.
=> Updated key's URL

src/extractors/rapidcloud.ts, src/extractors/vidcloud.ts
**Summary**
It can take a few minutes before the raw files get updated, so it's better to get the keys directly from github.com.
=> Using non-cached pages to get the keys

src/extractors/gogocdn.ts
fixes issue where sub sources not returning due to undefined resolutions
hell nah
hell nah
**Summary**
tommy stole my commit
=> fix undefined issue

src/providers/anime/kamyroll.ts
fix to `get` change referred api repo and cs repo
=> fix kamyroll

.github/workflows/npm-publish.yml, package.json
This version undo's the version for 1.3.1 and adds `npm run build` before publishing.
=> Undo version to 1.3.1

.github/dependabot.yml
=> ignore axios in dependabot

.github/workflows/remove-npm-package.yml
This adds the ability to remove npm version in case of requiring to unpublish a version.
**Summary**
=> Add workflow to remove npm version

src/providers/anime/enime.ts
added subtitles when using enime
no
no
**Summary**
no
no
=> subtitles now returns when using enime, if available

src/extractors/streamsb.ts, src/providers/anime/kamyroll.ts
- fix streamsb 
- and kamyroll logo
bugfixes
=> fix streamsb and kamyroll logo

docs/providers/zoro.md, src/providers/anime/zoro.ts
Exposes MAL ID from zoro
no
no
**Summary**
They were so nice to provide a MAL ID for us, so might as well expose it, makes figuring out anime ID so much easier
=> feat: add MAL ID to zoro anime info

src/models/base-parser.ts
New Functionality
No
No
**Summary**
Allow devs to change proxies after parser construction. Can be used to change proxies for PROVIDER_LIST.
N/A
=> feat: add proxy change method

src/providers/meta/anilist.ts
=> fix mal is undefined

src/extractors/kwik.ts
fix kwik extractor wrong cors url
=> fix kwik extractor wrong cors url 

src/providers/manga/mangasee123.ts
fix wrong cors proxy in mangasee123
=> fix wrong cors proxy in mangasee123

src/providers/meta/mal.ts
=> added popularity to mal

src/models/base-parser.ts, src/providers/meta/mal.ts
=> Mal popularity

src/providers/meta/anilist.ts
add currentEpisodeCount to Anilist
=> feat(anilist) add currentEpisodeCount

src/providers/anime/zoro.ts
Added "totalPages" count for any search query, so that anyone using this api can build a pagination feature on top of it.
=> feat (zoro): added totalPages count

src/providers/anime/marin.ts, src/providers/meta/anilist.ts
- add colour to some Anilist functions
- recent episodes
- trending 
- popular
=> feat(anilist) add colour to functions

src/providers/anime/marin.ts
Just a nullish check if alt_titles has Synonym property, if not return an empty array.
No I'm lazy as heck
Nope.
**Summary**
Eh self explanatory
=> fix(marin): fix in case anime doesn't has synonyms

src/models/base-parser.ts, src/utils/index.ts, src/utils/utils.ts
for some reason importing toMap from utils/index.ts will cause errors 
ran tests with previous commits 21 failed
new code passed
=> fixes "working code"

src/extractors/vizcloud.ts, src/providers/anime/9anime.ts
=> Fixed 9anime

src/providers/anime/marin.ts
=> chore(marin): remove logging 🙏

src/extractors/vidcloud.ts
Removed VidCloud extractor decryption due to no longer being needed to extract sources from FlixHQ.
=> VidCloud Extractor Issue

src/providers/anime/animesaturn.ts, src/providers/anime/index.ts
Adds some weird Italian provider 
Nope
Nope
**Summary**
This is adds a provider that has spanish subs. 
I got board (like the wood) so I felt like doing something. Also first time opening this project dont know if my routing is correct.
=> add animesaturn.tv provider

examples/solo-leveling.ts, package.json, src/providers/manga/asurascans.ts, src/providers/manga/index.ts, test/manga/asurascans.test.ts
- added new manga provider (AsuraScans)
- implements cloudflare bypass
-yes
-no
**Summary**
- trying to solve major problem for web scraping when cloudflare is enabled
- heavily inspired from tachiyomi asura extension
my first pull request, excuse my grammar
=> added Asurascans Provider

src/providers/manga/flamescans.ts, src/providers/manga/index.ts, src/utils/providers-list.ts, test/manga/flamescans.test.ts
new provider (Flamescans)
yes
no
**Summary**
- another manhwa provider by mangathesia 
- special thanks to tachiyomi inspiration
nothing
=> feat: added new provider (Flamescans)

src/extractors/kwik.ts, src/models/types.ts, src/providers/anime/animepahe.ts, test/anime/animepahe.test.ts
- removed dead cors proxy
- bug fixed fetching anime info and sources
- modified animepahe.test.ts for fetching sources
- no
**Summary**
Maybe someone update documentation for animepahe since i used episode url instead of episode id on fetching vid sources.
=> fix(animepahe): removed cors proxy, fixed fetching info and episodes

src/providers/anime/gogoanime.ts
Add has next page on genre route's response on gogoanime routes for easier pagination for api users
No
No
**Summary**
- Add has next page on response of genre route of gogoanime for easier pagination
=> feat: add has next page on genre route gogoanime

src/providers/manga/comick.ts
*What kind of change does this PR introduce?*
- bugfix
*Did you add tests for your changes?*
- No
*If relevant, did you update the documentation?*
- No
*Summary*
- Fix deprecated api used in `fetchAllChapters` and `getComicId`.
- typo in `ChapterData`
*Other information*
Not a native speaker, excuse my grammar
=> fix: `ComicK` provider

src/extractors/rapidcloud.ts
=> fix(rapidcloud): changed ajax route

src/providers/anime/zoro.ts
=> change baseURL to accommodate for Aniwatch

src/providers/manga/mangasee123.ts
Mangasee123 fix
**Summary**
Mangasee123.ts was not working because of deadlink variable `sgProxy` and its working fine without that proxy variable.
=> mangasee123 fix

src/providers/meta/anilist.ts, test/meta/anilist.test.ts
=> fixed anilist airing schedule

src/providers/movies/dramacool.ts
Added Subtitle type to know if the series/movies are Subtitled/Raw/Dubbed. This is a small edit and should work
=> Added type to all episodes dramacool.ts

src/providers/movies/viewAsian.ts
I saw there was no thumbnail in viewAsian so I added hopefully it will get merged ☺️
=> viewAsian: thumbnail

src/providers/anime/anify.ts
- Update Anify to use new search schema.
- Add the ability to use the `/media` route for `fetchAnimeInfoByAnilistId()`.
N/A
N/A
**Summary**
Fixes the Anify provider and hopefully improves the AniList lib.
N/A
=> fix: Anify

src/extractors/vidcloud.ts
Yes
No
**Summary**
Change back to github based keys since the key is stable and its written in RUST
Solves the website https://keys4.fun from getting too many requests
=> Switch rabbitstream keys back to github based

docs/providers/flixhq.md, src/providers/movies/flixhq.ts, test/movies/flixhq.test.ts
This change will add the possibility to fetch movies/tv series by genre at flixhq.
Yes
Not yet.
**Summary**
Closes #475
=> Add genre route to flixHQ provider

src/providers/anime/zoro.ts
bugfix
**Summary**
Fixed hasNextPage always returning true when searching using zoro
=> fix(zoro): fixed hasNextPage always being true

src/providers/movies/index.ts, src/providers/movies/turkish123.ts, test/movies/turkish123.test.ts
_Added Turkish123_
_Sure did_
_Nope_
=> added turkish123

src/providers/anime/9anime.ts
fixes the domain for 9anime as it rebranded
**Summary**
pizza
=> fix(9anime) Update domain

package.json
Adds the `domhandler` dependency needed by mangasee.ts 
Not needed
**Summary**
=> chore: Add Missing domhandler dep

docs/providers/zoro.md, src/providers/anime/zoro.ts, test/anime/zoro.test.ts
Added continue watching, it allows the user to get the in process anime from zoro using the cookies
Yes,I have added the test for the PR
=> feat: zoro - added continue watching

src/models/proxy.ts
=> fix(proxy): fix an issue where an array is passed to interceptor

src/extractors/gogocdn.ts, src/providers/movies/sflix.ts, test/anime/gogoanime.test.ts
Bug fix for gogoanime streaming links
Yeah
=> Added null safety

README.md
Changed the license badge from MIT to GPL-3.0. The previous badge incorrectly displayed the license as MIT, while the project is licensed under GPL-3.0. Updated the shields.io badge URL to reflect the correct license type.
=> docs: Update README.md 

src/providers/anime/zoro.ts
Refactoring
Yes
**Summary**
Update baseUrl of zoro provider
None
=> Revert back to hianime.to because its back
